### ISSUE TITLE
Particles seems to goes left

### ISSUE THREAD

**Issue by warnotte** [Ealrann/VSand#14]
If you just drop some water in empty space you'll see that particles will go slightly to the left.

**Comment by warnotte** [comment]
Is it related to that comment in file "Game_Step1_ChooseTo.comp" ? 

```
// We prefer right side. Left is naturally favourized due to
// the course of the shader: left to right.
```

**Comment by Ealrann** [comment]
Hello, thank you for reporting the problem.
Yes, it's related to that. Since the left side is the first to be computed, it has all freedom to move (so the right side has "less freedom"). So I tried to tweak it to avoid that, but I'm not sure this code is still relevant.
I will take a look this afternoon.

**Comment by warnotte** [comment]
Hi,

I did a SandFall game years ago (http://renaud.warnotte.be/SandFallGame) and had the same behaviour.

I was making a for loop from bottom to up, then nested a for loop from left to right. And of course that give a "less freedom" situation like this.

Then I don't remember exactly (and I loose my source code...) but i think i did something like making one time a for X loop from 0 to width then a for X loop from width to 0. (and maybe something else i don't remember). 

If it can help ;)

**Comment by Ealrann** [comment]
Ok, the previous commit fix it. 

In fact, now I use "transactions" to correctly parallelize the computation. For each particle: 
- 1/ If we can move, chose a target neighbour.
- 2/ If no target, check the neighbours, and accept one to come.
- 3/ Swap the cells (== accept the transaction if both cells want the same thing).

This way, I shouldn't have any problem of "freedom". Since I still had some drifting, I guessed it was still this problem...

Finally, the problem was a bad use of the random number (using the same for two related operations). 

Thank you for opening this issue ! It will be included in the next release (But I don't know when for now, no time).

_________

Your sand game looks good ! 

I wanted to add some pressure information in mine too, to solve the sad flow of particles. But, lack of time... I will probably do it one day.

**Comment by warnotte** [comment]
No problem, you're welcome. It's been a while a was waiting to see if somebody can code something using GPU to "solve" this kind of sandfall game :)

**Comment by warnotte** [comment]
Compiled and test with last change seems to be ok now :)
