### ISSUE TITLE
Building instructions are broken

### ISSUE THREAD

**Issue by kvark** [Ealrann/VSand#23]
> cd VSand/VSand/

There is no `VSand` folder here any more?

**Comment by Ealrann** [comment]
I just made a fresh clone, looks ok to me. 
Did you use the following command to clone ? 
```
git clone --recursive --single-branch --branch root https://github.com/Ealrann/VSand.git
```

**Comment by kvark** [comment]
Ah, branch root, hmm. Any reason this isn't the default branch in this repo?

**Comment by Ealrann** [comment]
Ah, I remember you use a specific pipeline when the `vkCapabilities.supportedUsageFlags` doesn't support Transfer. 
I made lot's of changes on the engine recently, and this pipeline looks broken. 
Let me some time to check it please :') (or you could clone from a commit (root branch) earlier than march 2020).

**Comment by kvark** [comment]
Oh fun:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fff34a9f6a7, pid=13385, tid=775
#
# JRE version: OpenJDK Runtime Environment AdoptOpenJDK (14.0+36) (build 14+36)
# Java VM: OpenJDK 64-Bit Server VM AdoptOpenJDK (14+36, mixed mode, sharing, tiered, compressed oops, g1 gc, bsd-amd64)
# Problematic frame:
# C  [CoreGraphics+0x736a7]  CGClipRetain+0xc
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/dmalyshau/Code/VSand/VSand/org.sheepy.vsand/hs_err_pid13385.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-support/issues
#
```
[hs_err_pid13385.log.zip](https://github.com/Ealrann/VSand/files/5126266/hs_err_pid13385.log.zip)

**Comment by Ealrann** [comment]
> Ah, branch root, hmm. Any reason this isn't the default branch in this repo?

Mhh indeed, I could consider making it the default branch.

**Comment by Ealrann** [comment]
> Oh fun

Yeah... Vulkan is really full of joy.

Shouldn't be too complex to fix, probably tomorrow !

**Comment by Ealrann** [comment]
Should be ok now. I'll add some test someday to check this pipeline automatically. 
To update the repo, go back to the root directory, and use 
```
git pull --recurse-submodules
```

**Comment by kvark** [comment]
```
> Task :org.sheepy.vsand:run FAILED
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fff33251924, pid=14248, tid=775
#
# JRE version: OpenJDK Runtime Environment AdoptOpenJDK (14.0+36) (build 14+36)
# Java VM: OpenJDK 64-Bit Server VM AdoptOpenJDK (14+36, mixed mode, sharing, tiered, compressed oops, g1 gc, bsd-amd64)
# Problematic frame:
# C  [HIToolbox+0x27924]  _ZNK22THIThemeTextInfoFinder10GetOptionsEv+0x8
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/dmalyshau/Code/VSand/VSand/org.sheepy.vsand/hs_err_pid14248.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-support/issue
```

**Comment by Ealrann** [comment]
Mhh, I don't reproduce the problem.

The `hs_errxxxx.log` doesn't contains the stacktrace by default; could you rerun it with `./gradlew run --stacktrace` please ? 

Do you have some validation layers ? If so, we could have more information too if you activate it :
1. If you use the VK_LAYER_KHRONOS_validation, go to step 2 directly. Otherwise, you need to add the layer name in the file `VSand/Lily-vulkan/org.sheepy.lily.vulkan.core/src/main/java/org/sheepy/lily/vulkan/core/instance/loader/Layers.java` (there is a static string list of enabled layers)
2. run the game with `./gradlew run --args "debug"`

**Comment by kvark** [comment]
[vsand-exception.txt](https://github.com/Ealrann/VSand/files/5130081/vsand-exception.txt)

> Task :org.sheepy.vsand:run FAILED
Assertion failed: (shape[0] == SHAPE_START), function assert_check_shape, file /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/CoreGraphics/CoreGraphics-1355.22/CoreGraphics/Regions/shape.c, line 161.

**Comment by Ealrann** [comment]
Ha, I'm a bit sad. I thought we could see more but no, this is only the gradle StackTrace.

I just tested on some other computers with different configuration/os, I saw no problems. 
Since it looks like the initial problem, could you check that the sub-module was correctly pulled please (the fix is there) : 
-> Is `VSand/Lily-vulkan` correctly on commit 56120596 ("Fix BackgroundImage compatibility pipeline") ?

**Comment by kvark** [comment]
I'm on rev 5e2c4bdf95e3375f1bf1c14ecb7adbf4ebb5ff1a
The lily-vulkan submodule is on 56120596ef9256fe058d620b6874553a202cc97e

**Comment by Ealrann** [comment]
Ok, it's the good version... I lack of ideas now.

I remember something else:
The last time you opened a ticket (in April), there was a problem with the version of GLFW, not compatible on mac. We fixed that by using the last snapshot version of LWJGL (they didn't made new release since, so it's likely that the problem is still there).
To update this version, simply edit the file `Lily-vulkan/gradle.properties`, and update the version of LWJGL like this : 
`lwjglVersion = 3.2.4-SNAPSHOT`

But well... it shouldn't lead to a segfault, so I'm not really confident... 

_____

Maybe the solution for now would be to use a previous version of VSand :
```
git clone --recursive --single-branch --branch root https://github.com/Ealrann/VSand.git
cd VSand/
git checkout 7fa5a9d
git submodule update
```

Then update LWJGL version : https://github.com/Ealrann/VSand/issues/20#issuecomment-609447558

```
cd VSand/
./gradlew run
```

**Comment by kvark** [comment]
With these exact steps, I'm back at:
> Exception in thread "main" java.lang.UnsatisfiedLinkError: Failed to locate library: libvulkan.1.dylib

**Comment by Ealrann** [comment]
Sorry for those problems. 
I spent some time to setup a macos VM (with virtualbox), but unfortunately, Metal doesn't support the virtual device there. So I still have no solutions to test/debug on macos.

About the error you got now, it reminds me [one of your previous post](https://github.com/Ealrann/VSand/issues/20#issuecomment-609463461) : 
You need to setup some *applicationDefaultJvmArgs* to the existing `application` block in `Vsand/VSand/org.sheepy.vsand/build.gradle` :
```
application {
	mainModule = 'org.sheepy.vsand'
	mainClass = 'org.sheepy.vsand.VSandApplicationLauncher'
	// mainClass = 'org.sheepy.vsand.VSandBenchmarkLauncher'

        applicationDefaultJvmArgs = ["-Dorg.lwjgl.util.DebugLoader=true", "-Dorg.lwjgl.glfw.checkThread0=false", "-Dorg.lwjgl.librarypath=/Users/dmalyshau/Code/vulkansdk/macOS/lib/", "-XstartOnFirstThread"]
}
```

Note : "-Dorg.lwjgl.util.DebugLoader=true" and "-Dorg.lwjgl.glfw.checkThread0=false" are probably useless here.

**Comment by kvark** [comment]
Thank you!
I was reading through those earlier discussions and got confused about 1) where to put this, and 2) whether this was needed. I think you said in one of the comments that it wasn't (anyway, not going to dig it up right now).

Adding this takes me further:
```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000012cf676d6, pid=20042, tid=775
#
# JRE version: OpenJDK Runtime Environment AdoptOpenJDK (14.0+36) (build 14+36)
# Java VM: OpenJDK 64-Bit Server VM AdoptOpenJDK (14+36, mixed mode, sharing, tiered, compressed oops, g1 gc, bsd-amd64)
# Problematic frame:
# C  [libMoltenVK.dylib+0xe56d6]  MVKCmdDispatch::encode(MVKCommandEncoder*)+0x46
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/dmalyshau/Code/VSand/VSand/org.sheepy.vsand/hs_err_pid20042.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
```
Unclear to me why MVK is used, when VK_ICD_FILENAMES is pointing to gfx-portability. Perhaps, VSand also links to MVK directly somehow?

**Comment by Ealrann** [comment]
When it'll work, I'll make a note somewhere to sum up the full procedure ! 

[This post of Spasi](http://forum.lwjgl.org/index.php?topic=6875.msg36239#msg36239) (maintainer of LWJGL) points that we need another jvmarg : `-Dorg.lwjgl.vulkan.libname=<path_to_vulkan_sdk>/macOS/lib/libvulkan.dylib`

Please try to add it to the `applicationDefaultJvmArgs` in the file `Vsand/VSand/org.sheepy.vsand/build.gradle`

Something like : 
```
application {
	mainModule = 'org.sheepy.vsand'
	mainClass = 'org.sheepy.vsand.VSandApplicationLauncher'
	// mainClass = 'org.sheepy.vsand.VSandBenchmarkLauncher'

        applicationDefaultJvmArgs = ["-Dorg.lwjgl.librarypath=/Users/dmalyshau/Code/vulkansdk/macOS/lib/", "-Dorg.lwjgl.vulkan.libname=/Users/dmalyshau/Code/vulkansdk/macOS/lib/libvulkan.dylib", "-XstartOnFirstThread"]
}
```

**Comment by kvark** [comment]
Alright, that works, at last 🎉 
I removed the other parameter ("-Dorg.lwjgl.librarypath") now.

<img width="1246" alt="Screen Shot 2020-08-31 at 10 56 04" src="https://user-images.githubusercontent.com/107301/91734297-c90e9380-eb78-11ea-9adb-3146a84c2e4a.png">

**Comment by Ealrann** [comment]
Thank you ! 

Issue #24 details the process to run on MacOS. Feel free to comment or to report something I'd have forgot. 
I'll try to make this process easier, especially since I still want to provide an official MacOS build for VSand. 

For now, I'm mainly waiting a new version of LWJGL since they made many fix for GLFW under MacOS.
Good luck with gfx-portability !
